package brmobi.moop.data.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import brmobi.moop.data.db.model.Condominio;
import brmobi.moop.data.network.model.User;

import brmobi.moop.data.db.dao.CondominioDao;
import brmobi.moop.data.db.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig condominioDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CondominioDao condominioDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        condominioDaoConfig = daoConfigMap.get(CondominioDao.class).clone();
        condominioDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        condominioDao = new CondominioDao(condominioDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Condominio.class, condominioDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        condominioDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CondominioDao getCondominioDao() {
        return condominioDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
